CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE PROJECTS(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TITLE VARCHAR(320) NOT NULL,
    ORGANISATION_ID UUID NOT NULL,
    SLUG VARCHAR(250),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_project_org
                    FOREIGN KEY(ORGANISATION_ID) REFERENCES ORGANISATIONS(ID),

    CONSTRAINT slug_unique
                    UNIQUE (SLUG)
);

CREATE INDEX IDX_PROJECT_ORGANISATION_ID ON PROJECTS(ORGANISATION_ID);
