CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE ORGANISATION_MEMBERS(
    ID uuid PRIMARY KEY  NOT NULL DEFAULT gen_random_uuid(),
    ORGANISATION_ID uuid NOT NULL,
    USER_ID uuid NOT NULL,
    NAME varchar(255),
    ROLE VARCHAR(255),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_member_org FOREIGN KEY (ORGANISATION_ID) REFERENCES organisations(ID),

    CONSTRAINT fk_member_user FOREIGN KEY(USER_ID) REFERENCES users(ID)
);

CREATE INDEX idx_org_member ON ORGANISATION_MEMBERS(ORGANISATION_ID);
CREATE INDEX idx_user_member ON ORGANISATION_MEMBERS(USER_ID);
