ALTER TABLE users
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE organisations
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE projects
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE organisation_members
    ALTER COLUMN id DROP DEFAULT;
